import type { Metadata } from "next";
import { Montserrat, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Asri LuckyStrike Garage",
  description: "Trusted vintage motorcycle repair and restoration services. Generated by DuaWorks Studio.",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/assets/images/AsriLuckyStrikeGarage.jpg", type: "image/jpeg" },
    ],
    shortcut: [
      { url: "/assets/images/AsriLuckyStrikeGarage.jpg", type: "image/jpeg" },
    ],
    apple: [
      { url: "/assets/images/AsriLuckyStrikeGarage.jpg" },
    ],
  },
  appleWebApp: {
    capable: true,
    title: "Asri LuckyStrike Garage",
    statusBarStyle: "black-translucent",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${oswald.variable} font-sans antialiased`}
      >
        <Navbar />
        <main className="min-h-screen bg-black text-white">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}